version: '3.9'

networks:
    default:
        external: true
        name: "${NETWORK}"

services:
  web:
    build: .
    image: "glife-${TAG}"
    environment:
      VIRTUAL_HOST: "${TAG}.${DOMAIN}"
      LETSENCRYPT_HOST: "${TAG}.${DOMAIN}"
