version: '3.9'

networks:
  default:
    external: true
    name: "${NETWORK}"

services:
  web:
    build: "https://github.com/lbacik/glife-web.git#${TAG}"
    image: "glife-${TAG}"
    environment:
      VIRTUAL_HOST: "${DOMAIN}, www.${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}, www.${DOMAIN}"
      APP_ENV: "prod"
      APP_VERSION: "${TAG}"
      JSONHUB_API: "${JSONHUB_API}"
      TEST_RESULT_V1_DEFINITION: "${TEST_RESULT_V1_DEFINITION}"
